# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applxy', '0002_auto_20160922_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('f', models.ManyToManyField(related_name='_person_f_+', to='applxy.Person')),
            ],
        ),
    ]
