# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applxy', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='purchase time')),
                ('days', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applxy.PurchaseHistory'),
        ),
    ]
