# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applxy', '0004_auto_20160922_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='days',
            field=models.IntegerField(),
        ),
    ]
