# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applxy', '0005_auto_20160922_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='person',
            name='f',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applxy.Person'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='PurchaseHistory',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
