# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applxy', '0006_auto_20160925_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='passwd',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
