# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applxy', '0015_remove_person_passwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField()),
                ('days', models.IntegerField()),
            ],
        ),
    ]
